dbt-public-profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PG_DB_HOST') }}"
      user: "{{ env_var('PG_DB_USER') }}"
      password: "{{ env_var('PG_DB_PASSWORD') }}"
      port: "{{ env_var('PG_DB_PORT') | int }}"
      database: "{{ env_var('PG_DB_NAME') }}"
      schema: "public"
